name: Update Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Update requirements
      run: |
        # Create requirements.in if it doesn't exist
        if [ ! -f requirements.in ]; then
          echo "# Core dependencies" > requirements.in
          echo "beautifulsoup4" >> requirements.in
          echo "requests" >> requirements.in
          echo "pandas" >> requirements.in
          echo "numpy" >> requirements.in
          echo "scikit-learn" >> requirements.in
          echo "openai" >> requirements.in
          echo "python-dotenv" >> requirements.in
          echo "psycopg2-binary" >> requirements.in
          echo "pytest" >> requirements.in
          echo "playwright" >> requirements.in
          echo "asyncio" >> requirements.in
        fi
        
        # Compile updated requirements
        pip-compile requirements.in

    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check -r requirements.txt || echo "Security vulnerabilities found - will be reported in PR"

    - name: Run tests with updated dependencies
      run: |
        pip install -r requirements.txt
        python -m pytest tests/ -x --tb=short || echo "Tests failed with updated dependencies"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: Weekly dependency update'
        body: |
          ## Automated Dependency Update
          
          This PR updates project dependencies to their latest versions.
          
          ### Changes
          - Updated `requirements.txt` with latest compatible versions
          - Ran security checks and tests
          
          ### Review Checklist
          - [ ] Check for breaking changes in updated packages
          - [ ] Verify all tests pass
          - [ ] Review security scan results
          - [ ] Test critical functionality manually if needed
          
          **Note:** This PR was automatically generated. Please review carefully before merging.
        branch: dependency-updates
        delete-branch: true

  security-audit:
    runs-on: ubuntu-latest
    needs: update-dependencies
    if: always()
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety bandit

    - name: Run security audit
      run: |
        echo "## Security Audit Report" > security-report.md
        echo "" >> security-report.md
        
        echo "### Safety Check (Known Vulnerabilities)" >> security-report.md
        safety check -r requirements.txt --output text >> security-report.md || true
        echo "" >> security-report.md
        
        echo "### Bandit Security Scan" >> security-report.md
        bandit -r . -f txt >> security-report.md || true

    - name: Upload security report
      uses: actions/upload-artifact@v4
      with:
        name: security-report
        path: security-report.md
