name: Run T4L Content Pipeline

on:
  schedule:
    - cron: '20 0,8-23 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      PYTHONPATH: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Pin Node for the Playwright Node driver ---
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Pin Playwright Python to a known-good version for your codebase
          # (adjust if you know the exact version you had when it worked)
          sed -i '1i playwright==1.47.0' requirements.txt
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Print runtime versions (sanity check)
        run: |
          node -v
          python -c "import sys,playwright; print('py', sys.version); print('playwright', playwright.__version__)"

      - name: Run article cleanup pipeline
        run: python scripts/cleanup_pipeline.py

      - name: Run article cluster pipeline
        run: python scripts/cluster_pipeline.py
