name: Run T4L Content Pipeline

on:
  schedule:
    # Run every 20th minute after the full hour, except between 01:00 and 08:00 UTC
    # This means it will run at 00:20, 08:20, 09:20, ..., 23:20 UTC
    - cron: '20 0,8-23 * * *'
  # Allow manual triggering
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env: # <-- Moved env block here
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      PYTHONPATH: .
      # Add any other environment variables used in your application
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium
          
      - name: Run article cleanup pipeline
        run: python scripts/cleanup_pipeline.py

      - name: Run article cluster pipeline
        run: python scripts/cluster_pipeline.py