name: Run Tests (DEPRECATED - Use CI workflow instead)

on:
  # Disable this workflow - use ci.yml instead
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: false  # Always skip this workflow
    steps:
      - name: Deprecated
        run: echo "This workflow is deprecated. Use the main CI workflow instead."
